### ISSUE TITLE
Should __init__ receive default field values?

### ISSUE THREAD

**Issue by vitawasalreadytaken** [brandjon/simplestruct#4]
It seems that a custom `__init__` function does not receive field values that were not passed to the constructor:

```
$ cat t.py
import simplestruct

class S(simplestruct.Struct):
    x = simplestruct.Field()
    y = simplestruct.Field(default = 0)

    def __init__(self, x, y):
        print('__init__ called with', x, y)

s1 = S(1, 2)
s2 = S(2)

$ python t.py
__init__ called with 1 2
Traceback (most recent call last):
  File "t.py", line 14, in <module>
    s2 = S(2)
  File "<snip>/env/lib/python3.4/site-packages/simplestruct/struct.py", line 149, in __call__
    inst = super().__call__(*args, **kargs)
TypeError: __init__() missing 1 required positional argument: 'y'
```

I find this rather confusing. To make `__init__` work with default values, I either have to ignore the arguments and access fields via `self.fieldname`, or duplicate default values in the signature of `__init__`.

**Comment by brandjon** [comment]
Thanks for pointing this out. It was indeed contrary to what was described at the bottom of examples/vector.py. FIxed in 60a7f99.
